import { Vocation, VocationIdentifier } from '../types/vocation.types.ts'

export const VOCATIONS: Record<VocationIdentifier, Vocation> = {
  KNIGHT: {
    id: 'KNIGHT',
    name: 'Knight',
    supplies: [
      'Ultimate healing rune',
      'Explosion rune',
      'Heavy magic missile rune',
      'Ice Heavy magic missile rune',
      'Great fireball rune',
      'Mana fluid',
      'Big mana Potion',
      'Ring of purity minutes',
      'Emberwake ring minutes',
      'Lionfish meal tier 1',
    ],
  },
  ARCHER: {
    id: 'ARCHER',
    name: 'Archer',
    supplies: [
      'Ultimate healing rune',
      'Explosion rune',
      'Heavy magic missile rune',
      'Ice Heavy magic missile rune',
      'Great fireball rune',
      'Sudden death rune',
      'Arrow',
      'Hunting arrow',
      'Piercing arrow',
      'Bolt',
      'Hunting bolt',
      'Burst Arrow',
      'Mana fluid',
      'Big mana Potion',
      'Ring of purity minutes',
      'Emberwake ring minutes',
      'Lionfish meal tier 1',
    ],
  },
  DRUID: {
    id: 'DRUID',
    name: 'Druid',
    supplies: [
      'Explosion rune',
      'Heavy magic missile rune',
      'Ice Heavy magic missile rune',
      'Great fireball rune',
      'Sudden death rune',
      'Small explosive rune',
      'Mana fluid',
      'Big mana Potion',
      'Ring of purity minutes',
      'Emberwake ring minutes',
      'Lionfish meal tier 1',
    ],
  },
  MAGE: {
    id: 'MAGE',
    name: 'Mage',
    supplies: [
      'Explosion rune',
      'Heavy magic missile rune',
      'Ice Heavy magic missile rune',
      'Great fireball rune',
      'Sudden death rune',
      'Small explosive rune',
      'Mana fluid',
      'Big mana Potion',
      'Ring of purity minutes',
      'Emberwake ring minutes',
      'Lionfish meal tier 1',
    ],
  },
}
