nodeLinker: node-modules
packageExtensions:
  "@angular-devkit/core@*":
    peerDependencies:
      "@types/ajv": "*"
      "chokidar": "*"
      "@types/chokidar": "*"
      "supports-color": "*"
      "@types/node": "*"

  "@nestjs/cli@*":
    peerDependencies:
      "chokidar": "*"
      "@types/chokidar": "*"
      "typescript": "*"
      "webpack": "*"
      "webpack-cli": "*"
      "@types/webpack": "*"
      "@types/webpack-cli": "*"
      "@types/node": "*"
      "@types/typescript": "*"

  "@typescript-eslint/project-service@*":
    peerDependencies:
      "typescript": "*"
      "@types/typescript": "*"

  "@typescript-eslint/parser@*":
    peerDependencies:
      "supports-color": "*"
      "@types/supports-color": "*"

  "fork-ts-checker-webpack-plugin@*":
    peerDependencies:
      "webpack": "*"
      "@types/webpack": "*"

