import { Item } from './item.types.ts'

export const ITEMS: Item[] = [
  {
    name: 'Gold Coin',
    value: 1,
  },
  {
    name: 'Platinum Coin',
    value: 100,
  },
  {
    name: 'Crystal Coin',
    value: 10000,
  },
  {
    name: 'Albino Scale Mail',
    value: 0,
    NPCs: ['Players'],
  },
  {
    name: 'Amulet of Loss',
    value: 45000,
    NPCs: ['Players'],
  },
  {
    name: 'Ancient Amulet',
    value: 500,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Ancient Armor',
    value: 75000,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Ancient Boots',
    value: 5000,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Ancient Helmet',
    value: 42000,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Ancient Legs',
    value: 45000,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Ancient Shield',
    value: 900,
    NPCs: ['Alesar'],
  },
  {
    name: 'Ancient Sword',
    value: 40000,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Angelic Boots',
    value: 95000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Angelic Helmet',
    value: 152000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Angelic Plate Armor',
    value: 222000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Angelic Platemail',
    value: 222000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Angry Soul',
    value: 20000,
    NPCs: ['Players'],
  },
  {
    name: 'Ankh',
    value: 100,
    NPCs: ['Yaman'],
  },
  {
    name: 'Aquamarine',
    value: 350,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Arcane Cowl',
    value: 45000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Arcane Kilt',
    value: 50000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Arcane Robe',
    value: 64500,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Arcane Shoes',
    value: 35000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Arming Sword',
    value: 20000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Ashlord Backpack',
    value: 0,
    NPCs: ['Players'],
  },
  {
    name: 'Ashlord Shield',
    value: 40000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Assassin Blade',
    value: 6300,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Assassin Dagger',
    value: 1000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Axe Ring',
    value: 400,
    NPCs: ['Players'],
  },
  {
    name: 'Barbarian Axe',
    value: 185,
    NPCs: ['Risdarick'],
  },
  {
    name: 'Bascinet',
    value: 24000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Battle Axe',
    value: 80,
    NPCs: ['Bronislav', 'Dietrich', 'Risdarick'],
  },
  {
    name: 'Battle Hammer',
    value: 120,
    NPCs: ['Andre', 'Bronislav', 'Dietrich', 'Glorin', 'Risdarick'],
  },
  {
    name: 'Battle Shield',
    value: 95,
    NPCs: ['Andre', 'Bronislav', 'Dosli', 'Risdarick', 'Valandril'],
  },
  {
    name: 'Black Crystal',
    value: 0,
    NPCs: ['Players'],
  },
  {
    name: 'Black Pearl',
    value: 280,
    NPCs: [
      'Annushka',
      'Asha',
      'Astrid',
      'Dianne',
      'Edea',
      'Leunaurd',
      'Lihsha',
      'Lona',
      'Rorin',
    ],
  },
  {
    name: 'Black Shield',
    value: 800,
    NPCs: ['Alesar'],
  },
  {
    name: 'Blazing Crossbow',
    value: 70000,
    NPCs: ['Aremis'],
  },
  {
    name: 'Blazing Greatsword',
    value: 300000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Blood Herb',
    value: 10000,
    NPCs: ['Players'],
  },
  {
    name: 'Blood Mace',
    value: 0,
    NPCs: ['Players'],
  },
  {
    name: 'Bloodcurser',
    value: 280000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Blue Gem',
    value: 25000,
    NPCs: [
      'Annushka',
      'Asha',
      'Astrid',
      'Dianne',
      'Edea',
      'Leunaurd',
      'Lihsha',
      'Lona',
      'Rorin',
    ],
  },
  {
    name: 'Blue Hood',
    value: 0,
    NPCs: ['Players'],
  },
  {
    name: 'Blue Robe',
    value: 10000,
    NPCs: ["Nah'Bob"],
  },
  {
    name: 'Blue Spellwand',
    value: 5000,
    NPCs: ['Haroun'],
  },
  {
    name: 'Bolt',
    value: 3,
    NPCs: ['Players'],
  },
  {
    name: 'Bone Shield',
    value: 100,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Boots of Haste',
    value: 30000,
    NPCs: ["Nah'Bob"],
  },
  {
    name: 'Brass Armor',
    value: 150,
    NPCs: ['Andre', 'Bronislav', 'Dietrich', 'Risdarick', 'Valandril'],
  },
  {
    name: 'Brass Helmet',
    value: 30,
    NPCs: ['Dosli', 'Hasain', 'Noranim', 'Valandril'],
  },
  {
    name: 'Brass Legs',
    value: 49,
    NPCs: ['Dosli', 'Hasain', 'Valandril'],
  },
  {
    name: 'Brass Shield',
    value: 16,
    NPCs: ['Dosli', 'Hasain', 'Valandril'],
  },
  {
    name: 'Bright Sword',
    value: 8000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Broad Sword',
    value: 500,
    NPCs: ["Nah'Bob"],
  },
  {
    name: 'Broken Whip',
    value: 23500,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Burst Arrow',
    value: 50,
    NPCs: ['Players'],
  },
  {
    name: 'Chain Armor',
    value: 70,
    NPCs: ['Bronislav', 'Dietrich', 'Risdarick', 'Valandril'],
  },
  {
    name: 'Chain Helmet',
    value: 17,
    NPCs: ['Bronislav', 'Dietrich', 'Noranim', 'Risdarick'],
  },
  {
    name: 'Chain Legs',
    value: 25,
    NPCs: ['Bronislav', 'Dietrich', 'Noranim', 'Risdarick', 'Valandril'],
  },
  {
    name: 'Chaos Shield',
    value: 2000000,
    NPCs: ['Players'],
  },
  {
    name: 'Chimera Mane',
    value: 80000,
    NPCs: ['Players'],
  },
  {
    name: 'Clerical Mace',
    value: 170,
    NPCs: ['Risdarick'],
  },
  {
    name: 'Club Ring',
    value: 100,
    NPCs: ['Haroun'],
  },
  {
    name: 'Crossbow',
    value: 160,
    NPCs: ['Aremis'],
  },
  {
    name: 'Crown Armor',
    value: 12000,
    NPCs: ["Nah'Bob"],
  },
  {
    name: 'Crown Boots',
    value: 12000,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Crown Helmet',
    value: 2500,
    NPCs: ["Nah'Bob"],
  },
  {
    name: 'Crown Legs',
    value: 12000,
    NPCs: ["Nah'Bob"],
  },
  {
    name: 'Crown Shield',
    value: 8000,
    NPCs: ["Nah'Bob"],
  },
  {
    name: 'Crusader Helmet',
    value: 6000,
    NPCs: ["Nah'Bob"],
  },
  {
    name: 'Crystal Ball',
    value: 190,
    NPCs: ['Jodi'],
  },
  {
    name: 'Crystallized Bow',
    value: 40000,
    NPCs: ['Aremis'],
  },
  {
    name: 'Crystallized Crossbow',
    value: 55000,
    NPCs: ['Aremis'],
  },
  {
    name: 'Crystallized Shield',
    value: 16000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Curved Axe',
    value: 1200,
    NPCs: ['Alesar'],
  },
  {
    name: 'Dark Armor',
    value: 400,
    NPCs: ['Alesar'],
  },
  {
    name: 'Dark Helmet',
    value: 250,
    NPCs: ['Alesar'],
  },
  {
    name: 'Dawnlight',
    value: 0,
    NPCs: ['Players'],
  },
  {
    name: 'Deathraze',
    value: 235000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Deepshadow Amulet',
    value: 340000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Deepshadow Boots',
    value: 200000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Deepshadow Legs',
    value: 285000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Deepshadow Mask',
    value: 245000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Deepshadow Robe',
    value: 325000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Demon Backpack',
    value: 0,
    NPCs: ['Players'],
  },
  {
    name: 'Demon Shield',
    value: 30000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Demonbone Armor',
    value: 40000,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Demonbone Boots',
    value: 14000,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Demonbone Helmet',
    value: 9000,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Demonic Axe',
    value: 215000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Devil Helmet',
    value: 1000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Double Axe',
    value: 260,
    NPCs: ['Aadim', 'Cord', 'Glorin', 'Horif'],
  },
  {
    name: 'Double Axe Head',
    value: 3000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Dragon Hammer',
    value: 2000,
    NPCs: ['Alesar'],
  },
  {
    name: 'Dragon Lance',
    value: 9000,
    NPCs: ["Nah'Bob"],
  },
  {
    name: 'Dragon Scale Mail',
    value: 30000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Dragon Shield',
    value: 4000,
    NPCs: ["Nah'Bob"],
  },
  {
    name: 'Dragon Slayer',
    value: 40000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Drake Scale Helmet',
    value: 850,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Dreadweave Robe',
    value: 600000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Dwarven Axe',
    value: 1500,
    NPCs: ['Alesar'],
  },
  {
    name: 'Dwarven Helmet',
    value: 0,
    NPCs: ['Players'],
  },
  {
    name: 'Dwarven Shield',
    value: 100,
    NPCs: ['Dosli'],
  },
  {
    name: 'Electric Armor',
    value: 10000,
    NPCs: ["Nah'Bob"],
  },
  {
    name: 'Electric Helmet',
    value: 5000,
    NPCs: ["Nah'Bob"],
  },
  {
    name: 'Electric Legs',
    value: 7000,
    NPCs: ["Nah'Bob"],
  },
  {
    name: 'Elite Knight Armor',
    value: 80000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Elite Knight Boots',
    value: 40000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Elite Knight Helmet',
    value: 52000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Elite Knight Legs',
    value: 60000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Elven Amulet',
    value: 100,
    NPCs: ['Haroun'],
  },
  {
    name: 'Ember Coin',
    value: 500,
    NPCs: ['Evona'],
  },
  {
    name: 'Emberwake Ring',
    value: 400000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Emberwake Tunic',
    value: 142000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Envenomed Crossbow',
    value: 65000,
    NPCs: ['Aremis'],
  },
  {
    name: "Executioner's Sword",
    value: 0,
    NPCs: ['Players'],
  },
  {
    name: 'Explosion Rune',
    value: 225,
    NPCs: ['Players'],
  },
  {
    name: 'Fiery Armor',
    value: 7500,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Fiery Bow',
    value: 150000,
    NPCs: ['Players'],
  },
  {
    name: 'Fiery Hammer',
    value: 20000,
    NPCs: ['Draculd'],
  },
  {
    name: 'Fiery Helmet',
    value: 7500,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Fire Axe',
    value: 8000,
    NPCs: ["Nah'Bob"],
  },
  {
    name: 'Fire Hammer',
    value: 20000,
    NPCs: ['Draculd'],
  },
  {
    name: 'Fire Sword',
    value: 4000,
    NPCs: ["Nah'Bob"],
  },
  {
    name: 'Fire Whip',
    value: 220000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Fireweaver',
    value: 4000,
    NPCs: ['Haroun'],
  },
  {
    name: 'Flaming Aegis',
    value: 375000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Flaming Bow',
    value: 18000,
    NPCs: ['Aremis'],
  },
  {
    name: 'Forgotten Soul',
    value: 30000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Frost Dagger',
    value: 800,
    NPCs: ['Draculd'],
  },
  {
    name: 'Frostwarden',
    value: 30000,
    NPCs: ['Haroun'],
  },
  {
    name: 'Frozen Shield',
    value: 29000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Gatecrasher',
    value: 4000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Giant Sword',
    value: 17000,
    NPCs: ['Alesar'],
  },
  {
    name: 'Golden Amulet',
    value: 1600,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Golden Armor',
    value: 20000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Golden Legs',
    value: 50000,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Golden Staff',
    value: 20000,
    NPCs: ['Draculd'],
  },
  {
    name: 'Gold Ring',
    value: 8000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Great Fireball Rune',
    value: 175,
    NPCs: ['Players'],
  },
  {
    name: 'Green Gem',
    value: 25000,
    NPCs: [
      'Annushka',
      'Asha',
      'Astrid',
      'Dianne',
      'Edea',
      'Leunaurd',
      'Lihsha',
      'Lona',
      'Rorin',
    ],
  },
  {
    name: 'Green Spellwand',
    value: 5000,
    NPCs: ['Haroun'],
  },
  {
    name: 'Grim Boots',
    value: 10000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Grim Legs',
    value: 30000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Guardian Halberd',
    value: 8000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Guardian Shield',
    value: 2000,
    NPCs: ["Nah'Bob"],
  },
  {
    name: 'Halberd',
    value: 400,
    NPCs: ['Bronislav', 'Dietrich', 'Risdarick'],
  },
  {
    name: 'Heart Backpack',
    value: 0,
    NPCs: ['Players'],
  },
  {
    name: 'Heart of Lightning',
    value: 0,
    NPCs: ['Players'],
  },
  {
    name: 'Heavy Frozen Missile Rune',
    value: 150,
    NPCs: ['Players'],
  },
  {
    name: 'Heavy Halberd',
    value: 35000,
    NPCs: ['Ziyad', 'Wulkan'],
  },
  {
    name: 'Heavy Magic Missile Rune',
    value: 75,
    NPCs: ['Players'],
  },
  {
    name: 'Heavy Truncheon',
    value: 300000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Hellforged Armor',
    value: 10000000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Hellforged Axe',
    value: 50000,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Hellforged Helmet',
    value: 12000000,
    NPCs: ['Players'],
  },
  {
    name: 'Hellforged Legs',
    value: 300000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Hellforged Shield',
    value: 36000,
    NPCs: ['Ziyad', 'Wulkan'],
  },
  {
    name: 'Holy Scepter',
    value: 50000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Hunting Arrow',
    value: 4,
    NPCs: ['Players'],
  },
  {
    name: 'Hunting Bolt',
    value: 5,
    NPCs: ['Players'],
  },
  {
    name: 'Hunting Bow',
    value: 1000,
    NPCs: ['Aremis'],
  },
  {
    name: 'Huntsman Armor',
    value: 0,
    NPCs: ['Players'],
  },
  {
    name: 'Ice Rapier',
    value: 1000,
    NPCs: ["Nah'Bob"],
  },
  {
    name: 'Icebound Helmet',
    value: 60000,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Ignited Bow',
    value: 5000,
    NPCs: ['Aremis'],
  },
  {
    name: 'Illumination Ring',
    value: 100,
    NPCs: ['Aremis'],
  },
  {
    name: 'Iron Helmet',
    value: 150,
    NPCs: ['Risdarick'],
  },
  {
    name: 'Imperial Soldier Armor',
    value: 5500,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Imperial Soldier Legs',
    value: 20000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Imperial Soldier Shield',
    value: 3000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Knight Armor',
    value: 5000,
    NPCs: ['Alesar'],
  },
  {
    name: 'Knight Axe',
    value: 2000,
    NPCs: ['Alesar'],
  },
  {
    name: 'Knight Helmet',
    value: 2500,
    NPCs: ['Alesar'],
  },
  {
    name: 'Knight Legs',
    value: 5000,
    NPCs: ['Alesar'],
  },
  {
    name: 'Lich Grimoire',
    value: 108000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Life Ring',
    value: 700,
    NPCs: ['Players'],
  },
  {
    name: 'Light Armor',
    value: 13000,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Light Sword',
    value: 4500,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Lightbringer Helmet',
    value: 40000,
    NPCs: ['Draculd'],
  },
  {
    name: 'Living Thunder',
    value: 1000,
    NPCs: ['Haroun'],
  },
  {
    name: 'Longsword',
    value: 51,
    NPCs: ['Dalos'],
  },
  {
    name: 'Mace',
    value: 30,
    NPCs: ['Bronislav', 'Dietrich', 'Risdarick'],
  },
  {
    name: 'Magic Plate Armor',
    value: 200000,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Magic Plate Boots',
    value: 80000,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Magic Plate Legs',
    value: 120000,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Mana Fluid',
    value: 100,
    NPCs: ['Players'],
  },
  {
    name: 'Mastermind Shield',
    value: 50000,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Medusa Shield',
    value: 8000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Mercenary Sword',
    value: 45000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Might Ring',
    value: 4000,
    NPCs: ['Players'],
  },
  {
    name: 'Mind Stone',
    value: 170,
    NPCs: ['Jodi'],
  },
  {
    name: 'Minotaur Tome',
    value: 0,
    NPCs: ['Players'],
  },
  {
    name: 'Morning Star',
    value: 54,
    NPCs: ['Aadim', 'Cord', 'Glorin', 'Horif'],
  },
  {
    name: 'Mystic Turban',
    value: 1000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Nether Shield',
    value: 6600,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Noble Armor',
    value: 900,
    NPCs: ["Nah'Bob"],
  },
  {
    name: 'Observer Helmet',
    value: 67000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Observer Shield',
    value: 82000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Obsidian Lance',
    value: 500,
    NPCs: ["Nah'Bob"],
  },
  {
    name: 'Orb',
    value: 750,
    NPCs: ['Haroun'],
  },
  {
    name: 'Permafrost Crystal',
    value: 3000,
    NPCs: ['Draculd'],
  },
  {
    name: 'Permafrost Longsword',
    value: 900,
    NPCs: ['Draculd'],
  },
  {
    name: 'Permafrost Morningstar',
    value: 1600,
    NPCs: ['Draculd'],
  },
  {
    name: 'Permafrost Robe',
    value: 26000,
    NPCs: ['Draculd'],
  },
  {
    name: 'Permafrost Stone',
    value: 7000,
    NPCs: ['Draculd'],
  },
  {
    name: 'Pharaoh Boots',
    value: 0,
    NPCs: ['Players'],
  },
  {
    name: 'Phoenix Backpack',
    value: 0,
    NPCs: ['Players'],
  },
  {
    name: 'Plaguespreader Robe',
    value: 26000,
    NPCs: ['Draculd'],
  },
  {
    name: 'Plaguespreader Rod',
    value: 2000,
    NPCs: ['Draculd'],
  },
  {
    name: 'Plate Armor',
    value: 400,
    NPCs: ['Andre', 'Bronislav', 'Dietrich', 'Risdarick', 'Valandril'],
  },
  {
    name: 'Plate Legs',
    value: 115,
    NPCs: ['Valandril'],
  },
  {
    name: 'Plate Shield',
    value: 45,
    NPCs: ['Dosli', 'Hasain'],
  },
  {
    name: 'Platinum Amulet',
    value: 1500,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Poisoned Bow',
    value: 16000,
    NPCs: ['Aremis'],
  },
  {
    name: 'Polished Amethyst',
    value: 2500,
    NPCs: ['Dianne', 'Edea', 'Evona', 'Leunaurd', 'Lihsha', 'Lizbeth'],
  },
  {
    name: 'Polished Emerald',
    value: 3000,
    NPCs: ['Dianne', 'Edea', 'Evona', 'Leunaurd', 'Lihsha', 'Lizbeth'],
  },
  {
    name: 'Polished Ruby',
    value: 3000,
    NPCs: ['Dianne', 'Edea', 'Evona', 'Leunaurd', 'Lihsha', 'Lizbeth'],
  },
  {
    name: 'Polished Sapphire',
    value: 3000,
    NPCs: ['Dianne', 'Edea', 'Evona', 'Leunaurd', 'Lihsha', 'Lizbeth'],
  },
  {
    name: 'Polished Topaz',
    value: 5000,
    NPCs: ['Dianne', 'Edea', 'Evona', 'Leunaurd', 'Lihsha', 'Lizbeth'],
  },
  {
    name: 'Protection Amulet',
    value: 100,
    NPCs: ['Yaman'],
  },
  {
    name: 'Purple Frozen Starlight',
    value: 0,
    NPCs: ['Players'],
  },
  {
    name: 'Quiver',
    value: 20000,
    NPCs: ['Players'],
  },
  {
    name: 'Red Dragon Scale',
    value: 0,
    NPCs: ['Players'],
  },
  {
    name: 'Red Frozen Starlight',
    value: 0,
    NPCs: ['Players'],
  },
  {
    name: 'Red Gem',
    value: 1000,
    NPCs: [
      'Annushka',
      'Asha',
      'Astrid',
      'Dianne',
      'Edea',
      'Leunaurd',
      'Lihsha',
      'Lona',
      'Rorin',
    ],
  },
  {
    name: 'Red Robe',
    value: 30000,
    NPCs: ['Players'],
  },
  {
    name: 'Red Skirt',
    value: 150,
    NPCs: ['Draculd'],
  },
  {
    name: 'Red Spellwand',
    value: 5000,
    NPCs: ['Haroun'],
  },
  {
    name: 'Red Tunic',
    value: 5000,
    NPCs: ['Draculd'],
  },
  {
    name: 'Ring of Healing',
    value: 2000,
    NPCs: ['Players'],
  },
  {
    name: 'Ring of the Sky',
    value: 20000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Ritual Dagger',
    value: 6000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Royal Helmet',
    value: 30000,
    NPCs: ["Nah'Bob"],
  },
  {
    name: 'Royal Plate Armor',
    value: 35000,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Ruby Necklace',
    value: 900,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Sacred Arbalest',
    value: 0,
    NPCs: ['Players'],
  },
  {
    name: 'Scale Armor',
    value: 75,
    NPCs: ['P.K.'],
  },
  {
    name: 'Scarab Amulet',
    value: 500,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Scarab Coin',
    value: 150,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Scarab Shield',
    value: 1500,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Scimitar',
    value: 150,
    NPCs: ['Alesar'],
  },
  {
    name: 'Scorpid Hood',
    value: 2300,
    NPCs: ["Nah'Bob"],
  },
  {
    name: 'Serpent Scepter',
    value: 1500,
    NPCs: ['Haroun'],
  },
  {
    name: 'Serpent Sword',
    value: 900,
    NPCs: ['Alesar'],
  },
  {
    name: 'Shadow Phoenix Backpack',
    value: 0,
    NPCs: ['Players'],
  },
  {
    name: 'Shadowfall',
    value: 15000,
    NPCs: ['Haroun'],
  },
  {
    name: 'Shadowfall Crossbow',
    value: 200000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Shakirian Blade',
    value: 35000,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Shakirian Bow',
    value: 32000,
    NPCs: ['Aremis'],
  },
  {
    name: 'Shakirian Shield',
    value: 3000,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Shakirian Spellbook',
    value: 1350,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Shakirian Wand',
    value: 6000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Shakirian Waraxe',
    value: 1000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Shield of the Heroes',
    value: 38000,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Silver Amulet',
    value: 50,
    NPCs: ['Yaman'],
  },
  {
    name: 'Silver Dagger',
    value: 500,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Silver Mace',
    value: 16500,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Skull Staff',
    value: 6000,
    NPCs: ['Alesar'],
  },
  {
    name: 'Skullbreaker',
    value: 78000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Small Amethyst',
    value: 200,
    NPCs: [
      'Annushka',
      'Asha',
      'Astrid',
      'Dianne',
      'Edea',
      'Leunaurd',
      'Lihsha',
      'Lona',
      'Rorin',
    ],
  },
  {
    name: 'Small Diamond',
    value: 300,
    NPCs: [
      'Annushka',
      'Asha',
      'Astrid',
      'Dianne',
      'Edea',
      'Leunaurd',
      'Lihsha',
      'Lona',
      'Rorin',
    ],
  },
  {
    name: 'Small Emerald',
    value: 250,
    NPCs: [
      'Annushka',
      'Asha',
      'Astrid',
      'Dianne',
      'Edea',
      'Leunaurd',
      'Lihsha',
      'Lona',
      'Rorin',
    ],
  },
  {
    name: 'Small Onyx',
    value: 460,
    NPCs: ['Astrid', 'Edea', 'Leunaurd', 'Lihsha'],
  },
  {
    name: 'Small Ruby',
    value: 250,
    NPCs: [
      'Annushka',
      'Asha',
      'Astrid',
      'Dianne',
      'Edea',
      'Leunaurd',
      'Lihsha',
      'Lona',
      'Rorin',
    ],
  },
  {
    name: 'Small Sapphire',
    value: 250,
    NPCs: [
      'Annushka',
      'Asha',
      'Astrid',
      'Dianne',
      'Edea',
      'Leunaurd',
      'Lihsha',
      'Lona',
      'Rorin',
    ],
  },
  {
    name: 'Small Topaz',
    value: 440,
    NPCs: [
      'Annushka',
      'Asha',
      'Astrid',
      'Dianne',
      'Edea',
      'Leunaurd',
      'Lihsha',
      'Lona',
      'Rorin',
    ],
  },
  {
    name: 'Soldier Helmet',
    value: 16,
    NPCs: ['P.K.'],
  },
  {
    name: 'Soul Dagger',
    value: 200,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Soul Reaper',
    value: 7500,
    NPCs: ['Draculd'],
  },
  {
    name: 'Soulstealer Armor',
    value: 218000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Spellbook',
    value: 75,
    NPCs: ['Yaman'],
  },
  {
    name: 'Spider Silk Armor',
    value: 2000,
    NPCs: ['Alesar'],
  },
  {
    name: 'Spike Sword',
    value: 1000,
    NPCs: ["Nah'Bob"],
  },
  {
    name: 'Spiked Club',
    value: 3200,
    NPCs: ['Alesar'],
  },
  {
    name: 'Sphinx Claw',
    value: 3000,
    NPCs: ['Arses'],
  },
  {
    name: 'Staff of Might',
    value: 5000,
    NPCs: ['Haroun'],
  },
  {
    name: 'Stealth Ring',
    value: 200,
    NPCs: ['Haroun'],
  },
  {
    name: 'Steel Boots',
    value: 30000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Steel Helmet',
    value: 293,
    NPCs: ['Dosli', 'Hasain', 'Noranim'],
  },
  {
    name: 'Steel Shield',
    value: 80,
    NPCs: ['Andre', 'Bronislav', 'Dietrich', 'Risdarick', 'Valandril'],
  },
  {
    name: 'Stone Skin Amulet',
    value: 4500,
    NPCs: ['Players'],
  },
  {
    name: 'Stormcaller',
    value: 8000,
    NPCs: ['Haroun'],
  },
  {
    name: 'Strange Helmet',
    value: 500,
    NPCs: ['Alesar'],
  },
  {
    name: 'Strange Symbol',
    value: 200,
    NPCs: ['Haffnal'],
  },
  {
    name: 'Sudden Death Rune',
    value: 300,
    NPCs: ['Players'],
  },
  {
    name: 'Swinging Demolisher',
    value: 16000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Sword',
    value: 25,
    NPCs: ['Aadim', 'Bronislav', 'Dalos', 'Dietrich', 'Risdarick'],
  },
  {
    name: 'Sword Ring',
    value: 100,
    NPCs: ['Haroun'],
  },
  {
    name: 'Syringe of Disease',
    value: 0,
    NPCs: ['Players'],
  },
  {
    name: 'Talon',
    value: 320,
    NPCs: ['Edea', 'Leunaurd', 'Lihsha'],
  },
  {
    name: 'Tainted Soul',
    value: 25000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'The Stinger',
    value: 7000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'The Sky Piercer',
    value: 16500,
    NPCs: ['Alesar'],
  },
  {
    name: 'Time Ring',
    value: 100,
    NPCs: ['Players'],
  },
  {
    name: 'Torn Quicksand Boots',
    value: 10000,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Tower Shield',
    value: 8000,
    NPCs: ['Alesar'],
  },
  {
    name: 'Two Handed Sword',
    value: 450,
    NPCs: ['Andre', 'Bronislav', 'Dalos', 'Dietrich', 'Risdarick'],
  },
  {
    name: 'Ultimate Healing Rune',
    value: 125,
    NPCs: ['Players'],
  },
  {
    name: 'Umbral Boots',
    value: 300000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Umbral Helmet',
    value: 300000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Umbral Plate Armor',
    value: 0,
    NPCs: ['Players'],
  },
  {
    name: 'Umbral Platemail',
    value: 0,
    NPCs: ['Players'],
  },
  {
    name: 'Umbral Robe',
    value: 0,
    NPCs: ['Players'],
  },
  {
    name: 'Unholy Halberd',
    value: 5500,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Unholy Plate Armor',
    value: 15000,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Vampire Shield',
    value: 15000,
    NPCs: ['Alesar'],
  },
  {
    name: 'Vanadinite Armor',
    value: 0,
    NPCs: ['Players'],
  },
  {
    name: 'Vanadinite Helmet',
    value: 36000,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Vanadinite Legs',
    value: 55000,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Vanquisher',
    value: 100000,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Venomous Mace',
    value: 75000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Violet Gem',
    value: 50000,
    NPCs: [
      'Annushka',
      'Asha',
      'Astrid',
      'Dianne',
      'Edea',
      'Leunaurd',
      'Lihsha',
      'Lona',
      'Rorin',
    ],
  },
  {
    name: 'Viking Helmet',
    value: 66,
    NPCs: ['Dietrich', 'Dosli', 'Hasain', 'Valandril'],
  },
  {
    name: 'Virulent Armor',
    value: 320000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Virulent Clawboots',
    value: 100000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Virulent Helmet',
    value: 130000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Virulent Legs',
    value: 225000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Venerator Mask',
    value: 500,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Void Mace',
    value: 150000,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Wand of Light',
    value: 4000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'War Hammer',
    value: 1200,
    NPCs: ["Nah'Bob"],
  },
  {
    name: 'Warlord Helmet',
    value: 42000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Warrior Helmet',
    value: 5000,
    NPCs: ['Alesar'],
  },
  {
    name: 'Watcher Armor',
    value: 125000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Watcher Boots',
    value: 85000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Watcher Legs',
    value: 110000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Watcher Shield',
    value: 7000,
  },
  {
    name: 'Webcrawler Boots',
    value: 53000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Webcrawler Shield',
    value: 12000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Wendigo Staff',
    value: 900,
    NPCs: ['Draculd'],
  },
  {
    name: 'White Pearl',
    value: 160,
    NPCs: [
      'Annushka',
      'Asha',
      'Astrid',
      'Dianne',
      'Edea',
      'Leunaurd',
      'Lihsha',
      'Lona',
      'Rorin',
    ],
  },
  {
    name: 'Wooden Maul',
    value: 2000,
    NPCs: ['Wulkan'],
  },
  {
    name: 'Yellow Gem',
    value: 2000,
    NPCs: [
      'Annushka',
      'Asha',
      'Astrid',
      'Dianne',
      'Edea',
      'Leunaurd',
      'Lihsha',
      'Lona',
      'Rorin',
    ],
  },
  {
    name: 'Yellow Robe',
    value: 18000,
    NPCs: ['Draculd'],
  },
  {
    name: 'Red Heels',
    value: 41500,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'War Axe',
    value: 80000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'High Heels of Seduction',
    value: 84000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Arcane Tunic',
    value: 125000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Plague Mask',
    value: 145000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Jade Tear',
    value: 165000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Ruby Tear',
    value: 165000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Jadeite Boots',
    value: 178000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'The Deathraze',
    value: 235000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Artifact of Penance',
    value: 250000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'The Bloodcurser',
    value: 280000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Mirror Shield',
    value: 310000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Umbral Legs',
    value: 335000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Chaos Axe',
    value: 600000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Chaos Mace',
    value: 600000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Chaos Sword',
    value: 600000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'The Dawnbringer',
    value: 600000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'The Lightbane',
    value: 600000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'The Twilight',
    value: 600000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'The Ward of Sheol',
    value: 625000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Solar Amulet',
    value: 666000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Hallowed Flame',
    value: 145000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Abyssal Scriptures',
    value: 8000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Abysmor Claw',
    value: 8000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Eyes of Abysmor',
    value: 8000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Hallowed Piece of Cloth',
    value: 6000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Prismatic Shard',
    value: 5000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Abyssal Fang',
    value: 5000,
    NPCs: ['Drolgruth'],
  },
  {
    name: 'Ritual Mask',
    value: 1400,
  },
  {
    name: 'Spider Silk',
    value: 40,
  },
  {
    name: 'Silver Elite Token',
    value: 0,
  },
  {
    name: 'Golden Elite Token',
    value: 0,
  },
  {
    name: 'Crystal Elite Token',
    value: 0,
  },
  {
    name: 'Crescent Axe',
    value: 60000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Crescent Bow',
    value: 60000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Crescent Mace',
    value: 60000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Crescent Sword',
    value: 60000,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Undead Dragon Trophy',
    value: 300000,
    NPCs: ['Draculd'],
  },
  {
    name: 'The Bonecrusher',
    value: 40000,
    NPCs: ['Ellara'],
  },
  {
    name: 'Hydra Ham',
    value: 0,
  },
  {
    name: 'Sling Herb',
    value: 0,
  },
  {
    name: 'Life crystal',
    value: 85,
    NPCs: ['Jodi'],
  },
  {
    name: 'Frozen Ham',
    value: 60,
  },
  {
    name: 'Frost Dragon Heart',
    value: 1600,
  },
  {
    name: 'Crystal Ring',
    value: 100,
    NPCs: ['Ziyad'],
  },
  {
    name: 'Silver Brooch',
    value: 125,
    NPCs: ['Dianne'],
  },
  {
    name: 'Small Topaze',
    value: 440,
    NPCs: ['Astrid'],
  },
  {
    name: 'Bow',
    value: 130,
    NPCs: ['Dalos'],
  },
  {
    name: 'Golden Mug',
    value: 1000,
    NPCs: ['Lona'],
  },
  {
    name: 'Shakirian Mace',
    value: 80,
    NPCs: ['Bronislav'],
  },
  {
    name: 'Small Onyxe',
    value: 460,
    NPCs: ['Edea'],
  },
  {
    name: 'Bonecrusher',
    value: 40000,
    NPCs: ['Ellara'],
  },
  {
    name: 'Crystal Necklace',
    value: 500,
    NPCs: ['Arses'],
  },
  {
    name: 'Dragonfetish',
    value: 200,
    NPCs: ['Jodi'],
  },
  {
    name: 'Energy Ring',
    value: 100,
    NPCs: ['Yaman'],
  },
]
