name: Api test

on : ['push']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build image
        run: docker build -t medivialyzer .

      - name: Test the project
        run: docker run medivialyzer sh -c "yarn workspace medivialyzer-api test"

      - name: Test the project (e2e)
        run: docker run medivialyzer sh -c "yarn workspace medivialyzer-api test:e2e"
