name: Client - Build - Ubuntu

on : ['push']

jobs:
  client-build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Yarn 4
        run: |
          corepack enable
          corepack prepare yarn@4.8.0 --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: Install Electron Builder dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfuse2 libappindicator1 libgconf-2-4 libnss3

      - name: Build the project
        run: yarn build:ci
