name: Frontend lint

on : ['push']

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build image
        run: docker build -t medivialyzer .

      - name: Lint the project
        run: docker run medivialyzer sh -c "yarn workspace medivialyzer-frontend lint"