name: Frontend test

on : ['push']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Build image
        run: docker build -t medivialyzer .

      - name: Lint the project
        run: docker run medivialyzer sh -c "yarn workspace medivialyzer-frontend test"