name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Yarn 4
        run: |
          corepack enable
          corepack prepare yarn@4.8.0 --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build the project
        run: yarn build:ci

      - name: Extract version from tag
        run: |
          echo "VERSION=${{ github.ref_name }}" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Zip folder using dynamic name
        run: Compress-Archive -Path src/packages/electron/dist_electron/* -DestinationPath "medivialyzer-$env:VERSION-win.zip"
        shell: pwsh

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v2
        with:
          name: medivialyzer-windows
          path: medivialyzer-${{ env.VERSION }}-win.zip

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Yarn 4
        run: |
          corepack enable
          corepack prepare yarn@4.8.0 --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build the project
        run: yarn build:ci

      - name: Extract version from tag
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Zip folder using dynamic name
        run: zip -r "medivialyzer-$VERSION-mac.zip" src/packages/electron/dist_electron/*

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v2
        with:
          name: medivialyzer-macos
          path: medivialyzer-${{ env.VERSION }}-mac.zip

  release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-macos]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Windows artifact
        uses: actions/download-artifact@v2
        with:
          name: medivialyzer-windows

      - name: Download macOS artifact
        uses: actions/download-artifact@v2
        with:
          name: medivialyzer-macos

      - name: Extract version from tag
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            medivialyzer-${{ env.VERSION }}-win.zip
            medivialyzer-${{ env.VERSION }}-mac.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
